ALTER TABLE TB_INDIVIDUOS
MODIFY telefone VARCHAR(15) NULL,
MODIFY rua VARCHAR(50) NULL,
MODIFY bairro VARCHAR(50) NULL,
MODIFY cidade VARCHAR(30) NULL,
MODIFY cep VARCHAR(10) NULL,
MODIFY estado VARCHAR(2) NULL;