ALTER TABLE TB_CONSULTAS_MEDICAS ADD CONSTRAINT tb_medicos_tb_consultas_medicas_fk
FOREIGN KEY (cod_medico)
REFERENCES TB_MEDICOS (cod_medico)
ON DELETE CASCADE
ON UPDATE NO ACTION;

ALTER TABLE TB_CONSULTAS_MEDICAS ADD CONSTRAINT tb_pacientes_tb_consultas_medicas_fk
FOREIGN KEY (cod_individuo)
REFERENCES TB_PACIENTES (cod_individuo)
ON DELETE CASCADE
ON UPDATE NO ACTION;